name: face_detection_overlay
description: flutter face detection with overlay image, built using Google ML Kit
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  camera: ^0.10.3
  google_mlkit_face_detection: ^0.5.0
  image: ^4.0.13
  outline_gradient_button: ^2.0.1+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
